### ISSUE TITLE
Jurassic Park/World

### ISSUE THREAD

**Issue by dstrus** [getfretless/appendix_n#17]
We listed Crichton's books separately, but the Jurassic movies deserve special mention.

Seeing _Jurassic World_ with MilesZS late at night after an Eleven Fifty class, and after driving to two different theaters, was one of my favorite movie-going experiences.

Also, I saw the first _Jurassic Park_ three times in the cinema during its first run.

**Comment by mileszs** [comment]
:+1:

I am adding these as movies. Sounds like they also deserve to be on the list as books, though. (PS I might want to borrow some Crichton books some day if you still have them.)
