### ISSUE TITLE
Chuck Palahniuk: Fight Club

### ISSUE THREAD

**Issue by unixmonkey** [getfretless/appendix_n#19]
The book was really good, but I think most people would agree the movie was better.

**Comment by mileszs** [comment]
I agree, and I disagree. The book was better, and I loved the movie. (My
bias is that I don't really like movies that much, though.)

**Comment by dstrus** [comment]
I like both, but there was something almost transcendent about the movie. One of the most perfectly adapted screenplays I can think of, and masterfully executed by all involved.

**Comment by mileszs** [comment]
In any case, it sounds like we all enjoyed both! Our differing of opinions
are marginal, and likely due to our preferred mediums.

**Comment by dstrus** [comment]
For sure. We are all clearly real-life nihilists.
