### ISSUE TITLE
Aldous Huxley: Brave New World

### ISSUE THREAD

**Issue by unixmonkey** [getfretless/appendix_n#5]

**Comment by mileszs** [comment]
I loved this book in high school, but I've forgotten much of it. I need to read it again! Or at least read a summary to be reminded of why I loved it so much.

**Comment by unixmonkey** [comment]
Babies are no longer born, but created in a lab, and are artificially selected and sorted to be part of "castes", so they give some babies fetal alcohol syndrome so they can be janitors and servants.

Those lucky enough to be born and sorted into the higher caste's live lives of luxury, promiscuity, and banality. Technology serves our every need, so critical thinking is discouraged, and those outside this city are savages.

**Comment by mileszs** [comment]
I remembered parts of that setting. What was the plot?

**Comment by unixmonkey** [comment]
Without giving too much away, they go to see the savages and bring one back, but he doesn't quite fit in, and it causes a bit of trouble in paradise.
