### ISSUE TITLE
Michael Crichton

### ISSUE THREAD

**Issue by unixmonkey** [getfretless/appendix_n#6]
I'm a fan of nearly all his books, but especially Jurassic Park and Sphere.

**Comment by dstrus** [comment]
:+1: 

I tore through his back catalog in junior high. JP and Sphere were favorites of mine, as well. Wrote a book report on Sphere.

The _Sphere_ move was terrible, but not nearly as bad as _Congo_, which I suspect I would find hilarious if I were to watch it again.

I also loved _The Terminal Man_ and _The Andromeda Strain_, the latter of which is a very quick read.

**Comment by unixmonkey** [comment]
Those are probably my #4 and #3 by him, too. Both are pretty short reads.

Fun fact, I read Sphere the first time in a single sitting. I think the paperback had around 600 pages. I don't know if I've ever read so much in a sitting since, but I couldn't put it down.

**Comment by mileszs** [comment]
Added. Someday I'll borrow these books from you guys or something.
