### ISSUE TITLE
Cronenberg: The Fly

### ISSUE THREAD

**Issue by unixmonkey** [getfretless/appendix_n#8]

**Comment by dstrus** [comment]
:+1: 

This movie is so good it hurts.

**Comment by unixmonkey** [comment]
"So, I asked the computer if it improved me and it said it
didn't know what I was talking about. And that's made me
think very carefully about what I've been feeling, and why.
And I'm beginning to think that the sheer process of being
taken apart atom by atom and put back together again, why
it's like coffee being put through a filter. It's somehow a
purifying process. It's purified me, it's cleansed me. And I
tell you, I think it's going to allow me to realize the
personal potential I've been neglecting all these years."

**Comment by mileszs** [comment]
Added. (I haven't seen any movie, of course. ;-)
